import { Metadata } from "next"

import {
  // blogPostSource,
  // blogPostSource2,
  blogsSource,
} from "@/lib/source"

import { Layout } from "@/features/blog/components/layout"
import { ContextProvider } from "@/features/blog/components/context"
import type { Tag, BlogPost } from "@/types"

const allBlogPosts = blogsSource.getPages().map<BlogPost>((blogPost) => {
  return {
    id: blogPost.path,
    title: blogPost.data.title,
    tags: blogPost.data.tags,
    createdAt: blogPost.data.createdAt,
    url: blogPost.url,
    path: blogPost.path,
    summary: blogPost.data.summary,
  }
})

export default async function Page() {
  // console.log("blogsSource.getPageTree", blogsSource.getPageTree())
  // console.log("page tree", blogPostSource.getPageTree())

  // console.log("allBlogPost", allBlogPost)
  // allBlogPost.map((blogPost) => {
  //   console.log(blogPost.data.getText)
  // })
  const allTags = collectAllTags(allBlogPosts)

  return (
    <ContextProvider>
      <Layout allTags={allTags} allBlogPosts={allBlogPosts} />
    </ContextProvider>
  )
}

const collectAllTags = (blogs: BlogPost[]) => {
  const tags: Tag[] = []
  blogs.forEach((blog) => {
    blog.tags.forEach((tagName) => {
      const targetTag = tags.find((tag) => tag.name === tagName)
      if (!targetTag) tags.push({ name: tagName, count: 1 })
      else targetTag.count++
    })
  })
  return tags
}

export const metadata: Metadata = {
  title: "博客 | lorem314.io",
  // description: "Generated by create next app",
}
