import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"

import { Layout } from "@/components/layout/layout"
import { TRPCProvider } from "@/trpc/client"

import "./globals.css"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "主页 | lorem314.io",
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <TRPCProvider>
          <Layout>{children}</Layout>
        </TRPCProvider>
      </body>
    </html>
  )
}

// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
